#' Create a ggplot map object
#'
#' @param layers, a list of `sf` objects, typically generated by [mapLayers()].
#'
#' @return
#' A `ggplot` object.
#'
#' @examples
#' library(osmdata)
#' bbox = getbb("Forchheim")
#' layertags = mapLayerTags(
#'   maptype = NULL
#'   , layers = c("roadsMajor", "roadsMinor")
#' )
#' layers = mapLayers(bbox, layertags = layertags)
#' mapOSM(layers, bg = "black", col = "white")
#'
#' @importFrom ggplot2 ggplot geom_sf coord_sf
#'
#' @export
mapOSM = function(
    location
    , maptype = "building"
    , design = "night"
    , options = mapOptions(maptype, design = design)
    , bg = "black"
    , title = NULL
    , subitle = NULL
){

    bbox = getbb(location)
    layertags = mapLayerTags(maptype)
    layers = mapLayers(bbox, layertags = layertags)

    p = ggplot2::ggplot()

    mapply(
        \(l, opts){
            ggplot2::geom_sf(
                data = l
                , inerits.aes = FALSE
            )
        }
        , l = layers
        , opts =
        , SIMPLIFY = FALSE
        , USE.NAMES = TRUE
    )

}

mapOptions = function(
    maptype
    , design
){

    bfg = switch(
        design
        , "night" = list(bg = "black", fg = "white")
        , "day" = list(bg = "white", fg = "black")
    )

    switch(
        maptype
        , "building" = list(
            color = c("steelblue", rep(bfg$fg, 3), "transparent")
            , fill = c(rep(NA, 4), bfg$fg)
            , size = c(0.8, 0.5, 0.4, 0.4, 0.8)
            , alpha = c(rep(0.8, 5))
            , lty = c("solid", "dotdash", rep("solid", 3))
            , bg = bfg$bg
        )
        , "street" = list(
            color = c("steelblue", rep(bfg$fg, 4))
            , fill = c(rep(NA, 5))
            , size = c(0.8, 0.5, 0.4, 0.4, 0.4)
            , alpha = c(rep(0.8, 5))
            , lty = c("solid", "dotdash", rep("solid", 3))
            , bg = bfg$bg
        )
    )

}


#' Query a set of map layers from the Overpass API
#'
#' @param bbox, an overpass_query object.
#' @param layertags, an object of class `mapLayerTags` listing all
#'   required map layers and associated feature tags. Typically created by
#'   [`mapLayerTags()`].
#'
#' @return
#' A list of `sf` objects.
#'
#' @examples
#' library(osmdata)
#' bbox = getbb("Forchheim")
#' layertags = mapLayerTags(
#'   maptype = NULL
#'   , layers = c("roadsMajor", "roadsMinor")
#' )
#' mapLayers(bbox, layertags = layertags)
#'
#' @importFrom osmdata opq add_osm_feature osmdata_sf
#'
#' @export
mapLayers = function(
    bbox
    , layertags
){

    ## argument checks
    stopifnot(
        "'bbox' must be a 2x2 'matrix'" = {
            inherits(bbox, what = "matrix")
        }
        , "'layerTags' must be of class 'MapLayerFeatureTags'!" =
            inherits(layertags, what = "MapLayerFeatureTags")
    )

    q = osmdata::opq(bbox)

    q_layers = lapply(
        layertags
        , FUN = \(i){
            osmdata::add_osm_feature(
                q
                , key = i$key
                , value = i$values
            )
        }
    )

    mapply(
        \(q, f) {
            l = osmdata::osmdata_sf(q)
            l = l[[f$geometry]]
            l[, c("osm_id", "name", "geometry")]
        }
        , q = q_layers
        , f = layertags
        , SIMPLIFY = FALSE
        , USE.NAMES = TRUE
    )

}


#' Create a feature list for a series of map layers.
#'
#' @details
#' This function consolidates feature tags for pre-defined map layers into a
#' list.
#'
#' @param maptype, a `character` indicating the default map type to be created.
#'   Currently supports "building" and "street". If set to `NULL`, a set of
#'   layers can be specified through `layers`.
#' @param layers, a `character` vector specifying the layers to be included in
#'   the map output. Can be any combination of "buildings", "roadsMajor",
#'   "roadsMinor", "roadsSmall", "rivers" and "railways". For each of these
#'   layers a standard set of features is included.
#'
#' @return
#' A nested `list` with layers and key-value-lists per layer.
#'
#' @examples
#' mapLayerTags(maptype = "building")
#' mapLayerTags(maptype = "street")
#' mapLayerTags(maptype = NULL, layers = c("buildings"))
#'
#' @export
mapLayerTags = function(
    maptype = "building"
    , layers = NULL
){

    ## argument checks
    match.arg(
        maptype
        , choices = c("building", "street")
        , several.ok = FALSE
    )

    match.arg(
        layers
        , choices = c(
            "buildings"
            , "roadsMajor"
            , "roadsMinor"
            , "roadsSmall"
            , "rivers"
            , "railways"
        )
        , several.ok = TRUE
    )

    if (!is.null(maptype) & !is.null(layers)) {
        warning("'maptype' is specified, 'layers' will be ignored!")
    }

    if (is.null(maptype)) {
        stopifnot(
            "'layers' must be a character vector!" = {
                inherits(layers, what = "character")
            }
        )
    }

    ## default layers for maptypes "building", "street"
    if (!is.null(maptype)) {
        layers = switch(
            maptype
            , "building" = c(
                "buildings"
                , "roadsMajor"
                , "roadsMinor"
                , "rivers"
                , "railways"
            )
            , "street" = c(
                "roadsMajor"
                , "roadsMinor"
                , "roadsSmall"
                , "rivers"
                , "railways"
            )
        )
    }

    ## create feature list
    l = mapply(
        \(l){
            switch(
                l
                , "buildings" = tagsBuildings()
                , "roadsMajor" = tagsRoadsMajor()
                , "roadsMinor" = tagsRoadsMinor()
                , "roadsSmall" = tagsRoadsSmall()
                , "rivers" = tagsRivers()
                , "railways" = tagsRailways()
            )
        }
        , l = layers
        , SIMPLIFY = FALSE
        , USE.NAMES = TRUE
    )

    structure(l, class = c("MapLayerFeatureTags", class(l)))

}

#' Functions to create key-value-lists per layer
tagsBuildings = function(){
    list(
        key = "building"
        , geometry = "osm_polygons"
        , values = c(
            "apartments"
            , "commercial"
            , "detached"
            , "house"
            , "residential"
            , "retail"
            , "semidetached_house"
            , "terrace"
            , "yes"
        )
    )
}

tagsRoadsMajor = function(){
    list(
        key = "highway"
        , geometry = "osm_lines"
        , values = c(
            "motorway"
            , "motorway_link"
            , "motorway_junction"
            , "primary"
            , "primary_link"
            , "trunk"
        )
    )
}

tagsRoadsMinor = function(){
    list(
        key = "highway"
        , geometry = "osm_lines"
        , values = c(
            "secondary"
            , "tertiary"
            , "secondary_link"
            , "tertiary_link"
        )
    )
}

tagsRoadsSmall = function(){
    list(
        key = "highway"
        , geometry = "osm_lines"
        , values = c(
            "residential"
            , "living_street"
            , "unclassified"
            , "service"
            , "footway"
            , "corridor"
            , "bridleway"
        )
    )
}

tagsRivers = function(){
    list(
        key = "waterway"
        , geometry = "osm_lines"
        , values = c(
            "river"
        )
    )
}

tagsRailways = function(){
    list(
        key = "railway"
        , geometry = "osm_lines"
        , values = c(
            "rail"
        )
    )
}
